yarnPath: .yarn/releases/yarn-3.3.1.cjs

defaultSemverRangePrefix: ""

pnpFallbackMode: all

pnpMode: loose

packageExtensions:
  "@mantine/styles@*":
    dependencies:
      "@emotion/cache": "*"
      "@emotion/react": "*"
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  "@prisma/client@*":
    dependencies:
      ".prisma": "link:/home/rouby/handy-hub/.yarn/unplugged/@prisma-client-virtual-824b2c72d1/node_modules/.prisma"
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"
  "@tiptap/core@*":
    dependencies:
      "prosemirror-commands": "*"
      "prosemirror-keymap": "*"
      "prosemirror-model": "*"
      "prosemirror-schema-list": "*"
      "prosemirror-state": "*"
      "prosemirror-transform": "*"
      "prosemirror-view": "*"
  "@tiptap/extension-link@*":
    dependencies:
      "prosemirror-model": "*"
      "prosemirror-state": "*"
  "@tiptap/extension-floating-menu@*":
    dependencies:
      "prosemirror-state": "*"
  "@tiptap/extension-dropcursor@*":
    dependencies:
      "prosemirror-dropcursor": "*"
  "@tiptap/extension-gapcursor@*":
    dependencies:
      "prosemirror-gapcursor": "*"
  "@tiptap/extension-history@*":
    dependencies:
      "prosemirror-history": "*"
  "@tiptap/extension-code-block@*":
    dependencies:
      "prosemirror-state": "*"
  "@tiptap/extension-horizontal-rule@*":
    dependencies:
      "prosemirror-state": "*"
